SQLインジェクションへの対処
soukun-so/lamp_practice pull request #6
Opened 2021-04-01 13:43 UTC by soukun-so

SQLインジェクションに対処するためのエスケープ処理を追加しました、確認お願いします。

2021-04-04 11:15 UTC, kamezaki01 requested changes

2021-04-04 11:15 UTC, kamezaki01 commented on www/model/db.php
> +function execute_query($db, $sql,$cart_id, $params = array()){
https://www.php.net/manual/ja/pdostatement.execute.php
こちらの仕様の通り、execute_query関数は変更なしで使えそうです。

2021-04-04 11:15 UTC, kamezaki01 commented on www/model/cart.php
> +  return execute_query($db, $sql,$cart_id);
execute_query($db, $sql, [$cart_id]);
execute_query($db, $sql, array($cart_id));

こういう感じで渡しましょう。

2021-04-05 13:28 UTC, soukun-so commented
関数 execute_query のみに変更し、cart_idは execute_query の引数 $param にて受け渡すように変更しました。
確認お願いします。

2021-04-07 10:55 UTC, kamezaki01 requested changes
やり方はOKです。
すべてのmodelをチェックして、適用できるところにはすべて適用しましょう。

2021-04-08 12:16 UTC, soukun-so commented
SQLを使用する箇所は全てバインドするように修正しました。
確認お願いします。

2021-04-11 00:56 UTC, kamezaki01 approved these changes
OKです！

2021-04-11 00:56 UTC, merged